### ISSUE TITLE
iXsystems

### ISSUE THREAD

**Issue by vermaden** [sirredbeard/Awesome-UNIX#2]
Under **UNIX and UNIX-Like Hardware Vendors** You can add **iXsystems** as FreeBSD hardware supplier.

**Comment by sirredbeard** [comment]
Thank you. [Added](2e0ea648ea05e37e1dfcf72da78d363f5eb18cb6).

**Comment by vermaden** [comment]
One more thing, iXsystems uses Supermicro servers/hardware for their offerings.

https://www.supermicro.com/
