### ISSUE TITLE
Correct or Source Better Venn Diagram

### ISSUE THREAD

**Issue by yuri-norwood** [sirredbeard/Awesome-UNIX#30]
## What is the problem
The  Venn Diagram is a useful isustration that I personally find more informative than the parallel timelines or tree diagrams used by Wikipedia to visually communicate the history of UNIX and related OSes. However, this diagram has many inaccuracies and is plainly wrong on several points.

## What is expected
* Haiku and Redox are not UNIX like, both have a terminal/shell interface, but in terms of both history and design both are completely independent.
* The "UNIX-Like" circle of the diagram is not really a useful separation. The line between what is "true" UNIX and what is merely "like" UNIX is a mile wide gradient, and I would argue that even "true" UNIX is still "UNIX like". This circle really just encapsulates all the OSes listed (save Haiku and Redox, as mentioned above), and I believe a better indication of the relationships of these systems would be for this circle to completely encapsulate the *nixes and be used to show the separation of Haiku et al.
* The "Descendants of AT&T UNIX" circle is really just two separate groups, BSDs and System V like systems. Unlike in most venn diagrams, these two categories are mutually exclusive (if my memory serves).
* The "Certified UNIX by the Open Group" circle is a in contrast a classification that in and of itself does not contain any systems inherently, this may be better shown as as sub-circle of the "UNIX like" circle, covering both BSDs and System Vs. Additionally, there are some (commercial) Linux distributions that have been certified, so these should also be acknowledged, perhaps by a tip of the Linux circle towards the "Unix like design" of the spectrum (which can be fleshed out with more examples but is otherwise solid).
* Since the defining trait of Linux (insert ~GNU/Linux~ GNU+Linux meme) is the Linux kernel, in addition to the BSD/System V split, the Unices should be divided by design, i.e. Linux/Hurd, BSD/SysV, DOS/DOS-like (DOS clones, Windows, ReactOS), BeOS/Haiku, Post-UNIX (Plan9, Inferno), and the odd balls (Temple OS, Redux).
* Lastly, MacOS is certified, but it also *is* a direct descendant of FreeBSD via Darwin and thus is not in it's own category but rather *is* a BSD.

## What can be done
There is an existing issue (#10) requesting that the image be recreated in a open format, presumably something with a trackable text representation like svg. If being recreated from scratch then it might as well be corrected at the same time.

I'm happy to volunteer myself to make a new infographic, if there is any interest.

### Proposed Hierarchy (where -> means 'influenced')
- UNIX like -> Plan 9 -> Inferno
  - BSD
    - FreeBSD -> Darwin -> MacOS
    - OpenBSD
    - NetBSD
  - System V
    - SunOS -> Solaris and friends
    - HP-UX
    - AIX
  - Minix -> Linux
    - Certified UNIX
    - Uncertified but keeping with UNIX philosophy
    - Uncertified and diverting from UNIX philosophy
  - GNU Hurd
- DOS line -> Windows -> React OS
  - DrDos
  - FreeDos
  - OS2
- BeOS -> Haiku
- Redux OS
- Retro MacOS -> MacOS (There isn't really a code ancestry but there is in design and philosophy)
- Temple OS

### Original
[![Venn Diagram](https://github.com/sirredbeard/Awesome-UNIX/blob/master/venn_diagram.png?raw=true)](https://github.com/sirredbeard/Awesome-UNIX/blob/master/venn_diagram.png)

**Comment by sirredbeard** [comment]
> a better indication of the relationships of these systems

The diagram isn't necessarily meant to delineate ancestry outside of the Descendants of AT&T UNIX section, it is more of a conceptual categorization diagram. I would be open to a diagram that better balances ancestry and categorization though.

> Haiku and Redox are not UNIX like

Redox and Haiku both aim for POSIX compatibility, so while they are not ancestors of any UNIX, I would argue they aim to be UNIX-like.

> BSDs and System V like systems

The BSDs are a branch of 4.4, if memory serves.

> I'm happy to volunteer myself to make a new infographic, if there is any interest.

I am interested if seeing what you put together.

I would suggest you provide it an an editable format, like .svg or a LibreOffice Draw file, so we can discuss and tweak.

There may be room for both a categorical and and an ancestral chart, trying to communicate both in one might be complicated.
