### ISSUE TITLE
opnSense

### ISSUE THREAD

**Issue by vermaden** [sirredbeard/Awesome-UNIX#5]
There was split in pfSense community and opnSense was/it a result of that split.

https://opnsense.org/

Probably its even better then pfSense because its more modern and make modification to vanilla FreeBSD as less as possible while pfSense modifies FreeBSD heavily.

**Comment by sirredbeard** [comment]
Thank you. [Added](https://github.com/sirredbeard/Awesome-UNIX/commit/7964996160d89e4ba395dab58b9dc66bd402a754).
