### ISSUE TITLE
A link to the BSD history as told by Marshall Kirk McKusick

### ISSUE THREAD

**Issue by debdrup** [sirredbeard/Awesome-UNIX#7]
The history of BSD has a pretty reliable source that can be linked to, in the form of Marshall Kirk McKusicks section of the Open Sources: Voices from the Open Source Revolution titled ["Twenty Years of Berkeley Unix - From AT&T-Owned to Freely Redistributable"](http://www.oreilly.com/openbook/opensources/book/kirkmck.html). Alternatively, there's also a ~3 hour [video](https://www.mckusick.com/history/index.html) where Kirk tells it all, including a lot of very charming asides and copious amounts of beer drinking, but it's up to you whether it should be linked to.

**Comment by sirredbeard** [comment]
Thank you. [Added](https://github.com/sirredbeard/Awesome-UNIX/commit/84720c2cf2aa4c0890e2aaed1d07ba41803fd75f).
